Repository BioJulia/BioServices.jl, pull requests merged in 2021-04, with the labels that each got.

#36 Modernize docs and CI
  .github/workflows/CompatHelper.yml
  .github/workflows/TagBot.yml
  .github/workflows/ci.yml
  .travis.yml
  Project.toml
  REQUIRE
  appveyor.yml
  docs/Project.toml
  docs/make.jl
  docs/src/man/gggenome.md
  src/eutils.jl
Labels: Documentation, enhancement

#41 update license links
  src/eutils.jl
  src/gggenome.jl
  src/umls.jl
Labels: Documentation

#37 WIP: Add EMBL-EBI Proteins REST API
  CHANGELOG.md
  src/BioServices.jl
  src/common.jl
  src/ebiproteins.jl
  src/eutils.jl
  test/ebiproteins.jl
  test/runtests.jl
Labels: enhancement
